### ISSUE TITLE
"Object-orientify" JavaScript

### ISSUE THREAD

**Issue by krulik** [yonimor/web-app#7]
Related code/functionality/state should be grouped and encapsulated into Objects/Classes.
It should be obvious without reading the whole code what are the entities/functionality which inhabit it.

**Comment by yonimor** [comment]
@krulik 
I'm finding this abit difficult to fully understand, I'd appreciate farther explanation (or example).

**Comment by krulik** [comment]
@yoni-mor 
Sure, here's a very simple example:

var Tabs = {
  activate: function () {},
  getPanel: function () {},
  hash: function () {},
  init: function () {}
};

var DropDowns = {
  closeDropdown: function () {},
  openDropdown: function () {},
  init: function () {}
};

Tabs.init(".tabs");
DropDowns.init(".dropdown");

**Comment by yonimor** [comment]
@krulik 
Thanks for the example, now it's pretty clear.
Please take a look at the updated main.js.

**Comment by krulik** [comment]
@yoni-mor 
Ok, it's one step in the direction.
Few things:
- [x] You still have stuff "hanging free" without any object scope
- [x] You don't need the "Obj" suffix, just use a good simple short name which describes the "thing" that it is. It's a convention to CapitalCase objects.
- [x] You have very long methods. A method any longer than the view fold should be refactored.
- [ ] You have too few objects. My rule of thumb is that any two methods and one variable that are related to the same piece of functionality/entity should be refactored away into an object.
- [x] Specifically, the name "interactivity" for an object is way too general and implies that it does too many things.

**Comment by yonimor** [comment]
@krulik 
Should I have objects inside objects? (like sub-modules), or just many independent objects?

**Comment by krulik** [comment]
@yoni-mor 

I would keep it simple at this stage, without sub-modules.
I doubt that you need one at this scale, but if you're absolutely sure about it than fine.

**Comment by krulik** [comment]
@yoni-mor 
Btw, great job! It looks much much better.
